dataSource:
  driverClassName: com.mysql.jdbc.Driver
  dbCreate: update
  username: root
  password: '1234'

server:
port: 8080

environments:
  development:
    dataSource:
      dbCreate: update
      url: "jdbc:mysql://localhost:3306/mascot?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"